export enum code {
    INVALID_FIELD_LENGTH,
    INVALID_FORMAT,
    INVALID_TYPE,
    INVALID_WHITESPACE,
    INVALID_NULL_VALUE,
    NOT_FOUND_RECORD,
    INVALID_FIELD_COUNT,
    INVALID_FIELD_MATCHING,
    INVALID_FIELD_TYPE_MATCHING,
}
