export default path_examples = [
    {
        input: "/home/user/boost/camp/challenge/day8/problem.md",
        output: {
            root: "C:",
            base: "problem.md",
            name: "problem",
            ext: ".md",
            components: [
                "C:",
                "home",
                "user",
                "boost",
                "camp",
                "challenge",
                "day8",
            ],
            absolute_string:
                "C:/home/user/boost/camp/challenge/day8/problem.md",
            exist_file: false,
        },
    },
    {
        input: "C:\\Users\\jwch1\\Repository\\boostcamp\\challenge\\day07\\problem.md",
        output: {
            root: "C:",
            base: "problem.md",
            name: "problem",
            ext: ".md",
            components: [
                "C:",
                "Users",
                "jwch1",
                "Repository",
                "boostcamp",
                "challenge",
                "day07",
            ],
            absolute_string:
                "C:/Users/jwch1/Repository/boostcamp/challenge/day07/problem.md",
            exist_file: true,
        },
    },
    {
        input: "/home/user/Documents/Project/file.txt",
        output: {
            root: "C:",
            base: "file.txt",
            name: "file",
            ext: ".txt",
            components: ["C:", "home", "user", "Documents", "Project"],
            absolute_string: "C:/home/user/Documents/Project/file.txt",
            exist_file: false,
        },
    },
    {
        input: "./boost/camp",
        output: {
            root: "C:",
            base: "camp",
            name: "camp",
            ext: undefined,
            components: [
                "C:",
                "Users",
                "jwch1",
                "Repository",
                "boostcamp",
                "day07",
                "boost",
            ],
            absolute_string:
                "C:/Users/jwch1/Repository/boostcamp/day07/boost/camp",
            exist_file: false,
        },
    },
    {
        input: "../user/boost/camp",
        output: {
            root: "C:",
            base: "camp",
            name: "camp",
            ext: undefined,
            components: [
                "C:",
                "Users",
                "jwch1",
                "Repository",
                "boostcamp",
                "user",
                "boost",
            ],
            absolute_string:
                "C:/Users/jwch1/Repository/boostcamp/user/boost/camp",
            exist_file: false,
        },
    },
    {
        input: "boost/camp",
        output: {
            root: "C:",
            base: "camp",
            name: "camp",
            ext: undefined,
            components: [
                "C:",
                "Users",
                "jwch1",
                "Repository",
                "boostcamp",
                "day07",
                "boost",
            ],
            absolute_string:
                "C:/Users/jwch1/Repository/boostcamp/day07/boost/camp",
            exist_file: false,
        },
    },
    {
        input: "/home",
        output: {
            root: "C:",
            base: "home",
            name: "home",
            ext: undefined,
            components: ["C:"],
            absolute_string: "C:/home",
            exist_file: false,
        },
    },
    {
        input: "home",
        output: {
            root: "C:",
            base: "home",
            name: "home",
            ext: undefined,
            components: [
                "C:",
                "Users",
                "jwch1",
                "Repository",
                "boostcamp",
                "day07",
            ],
            absolute_string: "C:/Users/jwch1/Repository/boostcamp/day07/home",
            exist_file: false,
        },
    },
];
