export default path_examples = [
    {
        input: "/home/user/boost/camp/challenge/day8/problem.md",
        output: {
            root: "/",
            base: "problem.md",
            name: "problem",
            ext: ".md",
            components: [
                "/",
                "home",
                "user",
                "boost",
                "camp",
                "challenge",
                "day8",
            ],
            absolute_string: "/home/user/boost/camp/challenge/day8/problem.md",
            exist_file: true,
        },
    },
    {
        input: "C:\\home\\user\\boost\\camp\\challenge\\day8\\problem.md",
        output: {
            root: "/",
            base: "problem.md",
            name: "problem",
            ext: ".md",
            components: [
                "/",
                "home",
                "user",
                "boost",
                "camp",
                "challenge",
                "day8",
            ],
            absolute_string: "/home/user/boost/camp/challenge/day8/problem.md",
            exist_file: true,
        },
    },
    {
        input: "/home/user/Documents/Project/file.txt",
        output: {
            root: "/",
            base: "file.txt",
            name: "file",
            ext: ".txt",
            components: ["/", "home", "user", "Documents", "Project"],
            absolute_string: "/home/user/Documents/Project/file.txt",
            exist_file: false,
        },
    },
    {
        input: "./boost/camp",
        output: {
            root: "/",
            base: "camp",
            name: "camp",
            ext: undefined,
            components: ["/", "home", "user", "day07", "boost"],
            absolute_string: "/home/user/day07/boost/camp",
            exist_file: false,
        },
    },
    {
        input: "../user/boost/camp",
        output: {
            root: "/",
            base: "camp",
            name: "camp",
            ext: undefined,
            components: ["/", "home", "user", "user", "boost"],
            absolute_string: "/home/user/user/boost/camp",
            exist_file: false,
        },
    },
    {
        input: "boost/camp",
        output: {
            root: "/",
            base: "camp",
            name: "camp",
            ext: undefined,
            components: ["/", "home", "user", "day07", "boost"],
            absolute_string: "/home/user/day07/boost/camp",
            exist_file: false,
        },
    },
    {
        input: "/home",
        output: {
            root: "/",
            base: "home",
            name: "home",
            ext: undefined,
            components: ["/"],
            absolute_string: "/home",
            exist_file: true,
        },
    },
    {
        input: "home",
        output: {
            root: "/",
            base: "home",
            name: "home",
            ext: undefined,
            components: ["/", "home", "user", "day07"],
            absolute_string: "/home/user/day07/home",
            exist_file: false,
        },
    },
];
